/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GearRouteImport } from './routes/gear'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiGoogleVisionRouteImport } from './routes/api/googleVision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleVisionRoute = ApiGoogleVisionRouteImport.update({
  id: '/api/googleVision',
  path: '/api/googleVision',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gear': typeof GearRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/api/googleVision': typeof ApiGoogleVisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gear': typeof GearRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/api/googleVision': typeof ApiGoogleVisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gear': typeof GearRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/api/googleVision': typeof ApiGoogleVisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gear' | '/scan' | '/settings' | '/api/googleVision'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gear' | '/scan' | '/settings' | '/api/googleVision'
  id: '__root__' | '/' | '/gear' | '/scan' | '/settings' | '/api/googleVision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GearRoute: typeof GearRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ApiGoogleVisionRoute: typeof ApiGoogleVisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/googleVision': {
      id: '/api/googleVision'
      path: '/api/googleVision'
      fullPath: '/api/googleVision'
      preLoaderRoute: typeof ApiGoogleVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GearRoute: GearRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ApiGoogleVisionRoute: ApiGoogleVisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
